name: Xefi
description: Application vendeur mobile

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  connectivity_plus: ^2.3.4
  dartz: ^0.10.1
  flutter_keyboard_visibility: ^5.3.0
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  encrypt: ^5.0.1
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1
  flutter_typeahead: ^4.0.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lazy_load_scrollview: ^1.3.0
  line_awesome_flutter: ^2.0.0
  package_info_plus: ^1.4.2
  universal_html: ^2.0.8
  url_launcher: ^6.1.3
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  flutter_downloader: ^1.8.0+1
  device_info_plus: ^3.2.4
  permission_handler: ^9.2.0
  flutter_svg: ^1.1.0
  syncfusion_flutter_calendar: ^20.1.60
  syncfusion_localizations: ^20.1.60
  time: ^2.1.1
  flutter_slidable: ^1.3.0
  confetti: ^0.7.0
  timeline_tile: ^2.0.0
  flutter_speed_dial: ^6.0.0
  sentry_flutter: ^6.5.1
  cached_network_image: ^3.2.1

dev_dependencies:
  build_runner: ^2.1.11
  dependency_validator: ^3.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  test: ^1.21.1

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#F8F8FA"
  image: assets/logo/Logo_WEB_Vendeur.png
  image_dark: assets/logo/Logo_WEB_Vendeur.png
  branding: assets/logo/branding_light.png
  branding_dark: assets/logo/branding_dark.png
  branding_mode: bottomRight
  color_dark: "#2B2E42"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: false
  ios: true
  image_path: "assets/logo/IOS_vendeur.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
# flutter pub run build_runner build --delete-conflicting-outputs
# RUN RC flutter run --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://rc-vendeur-api.xefi-apps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://rc-translation-api.xefi-apps.fr/api" --dart-define="AUTH_API_BASE_URL=https://rc-authprovider-api.xefi-apps.fr/api" --dart-define="XEFI_APPS_URL=https://rc-app.xefi-apps.fr" --dart-define="ENV_TYPE=RC" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD APK RD flutter build apk --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://rd-vendeur-api.xefi-apps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://rd-translation-api.xefi-apps.fr/api" --dart-define="AUTH_API_BASE_URL=https://rd-authprovider-api.xefi-apps.fr/api" --dart-define="XEFI_APPS_URL=https://rd-app.xefi-apps.fr" --dart-define="ENV_TYPE=RD" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD IOS RD flutter build ios --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://rd-vendeur-api.xefi-apps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://rd-translation-api.xefi-apps.fr/api" --dart-define="AUTH_API_BASE_URL=https://rd-authprovider-api.xefi-apps.fr/api" --dart-define="XEFI_APPS_URL=https://rd-app.xefi-apps.fr" --dart-define="ENV_TYPE=RD" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD APK RC flutter build apk --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://rc-vendeur-api.xefi-apps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://rc-translation-api.xefi-apps.fr/api" --dart-define="AUTH_API_BASE_URL=https://rc-authprovider-api.xefi-apps.fr/api" --dart-define="XEFI_APPS_URL=https://rc-app.xefi-apps.fr" --dart-define="ENV_TYPE=RC" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD IOS RC flutter build ios --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://rc-vendeur-api.xefi-apps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://rc-translation-api.xefi-apps.fr/api" --dart-define="AUTH_API_BASE_URL=https://rc-authprovider-api.xefi-apps.fr/api" --dart-define="XEFI_APPS_URL=https://rc-app.xefi-apps.fr" --dart-define="ENV_TYPE=RC" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD APK PROD flutter build apk --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://vendeur-api.dailyapps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://translation-api.dailyapps.fr/api" --dart-define="AUTH_API_BASE_URL=https://authprovider-api.dailyapps.fr/api" --dart-define="XEFI_APPS_URL=https://app.dailyapps.fr" --dart-define="ENV_TYPE=PROD" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD IOS PROD flutter build ios --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://vendeur-api.dailyapps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://translation-api.dailyapps.fr/api" --dart-define="AUTH_API_BASE_URL=https://authprovider-api.dailyapps.fr/api" --dart-define="XEFI_APPS_URL=https://app.dailyapps.fr" --dart-define="ENV_TYPE=PROD" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD BUNDLE PROD flutter build appbundle --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://vendeur-api.dailyapps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://translation-api.dailyapps.fr/api" --dart-define="AUTH_API_BASE_URL=https://authprovider-api.dailyapps.fr/api" --dart-define="XEFI_APPS_URL=https://app.dailyapps.fr" --dart-define="ENV_TYPE=PROD" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
# BUILD ARCHIVE PROD flutter build ipa --release --dart-define="APP_UUID=17139ea5-2aa5-5117-abc3-2c065332c447" --dart-define="BASE_URL=https://vendeur-api.dailyapps.fr/api" --dart-define="TRANSLATION_BASE_URL=https://translation-api.dailyapps.fr/api" --dart-define="AUTH_API_BASE_URL=https://authprovider-api.dailyapps.fr/api" --dart-define="XEFI_APPS_URL=https://app.dailyapps.fr" --dart-define="ENV_TYPE=PROD" --dart-define="RANDOM=f9YDmKYBNHyOwb0KqxRCQd7PV6U4oZfAsAIAa2w28e4="
